---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves

Did gyre and gimble in the wabe:

All mimsy were the borogoves,

And the mome raths outgrabe.

“Beware the Jabberwock, my son!

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Builder, in building the little house,

In every way you may please yourself;

But please please me in the kitchen chimney:

Don’t build me a chimney upon a shelf.

However far you must go for bricks,

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,

Shining with all his might:

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
The way the universe sat waiting to become,

quietly, in the nether of space and time,

you too remain some cellular snuggle

dangling between my legs, curled in the warm

swim of my mostly quietest self. If you come to be—

And who knows?—I wonder, little bubble

of unbudded capillaries, little one ever aswirl

in my vascular galaxies, what would you think

of this world which turns itself steadily

into an oblivion that hurts, and hurts bad?
